export const actionType = {
  FETCH__USER__SUCCESS: "FETCH__USER__SUCCESS",
  FETCH__USER__ISLOADING: "FETCH__USER__ISLOADING",
  FETCH__USER__ERROR: "FETCH__USER__ERROR",

  FETCH__USERDETAIL__SUCCESS: "FETCH__USERDETAIL__SUCCESS",
  FETCH__USERDETAIL__ISLOADING: "FETCH__USERDETAIL__ISLOADING",
  FETCH__USERDETAIL__ERROR: "FETCH__USERDETAIL__ERROR",

  FETCH__USERFOLLOW__SUCCESS: "FETCH__USERFOLLOW__SUCCESS",
  FETCH__USERFOLLOW__ISLOADING: "FETCH__USERFOLLOW__ISLOADING",
  FETCH__USERFOLLOW__ERROR: "FETCH__USERFOLLOW__ERROR",
};
